---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
  slides:
    default_front_matter_template: slides
  talks:
    default_front_matter_template: talks
  blog:
    default_front_matter_template: blog
upload_dir: static/media
public_path: "/media"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:filename:"
version: 0.27.1
